services:
  web:
    container_name: resume-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nav/certs:/etc/nginx/nav/ssl
      - ./nav/html:/var/www/html
      - php-socket:/var/run/php
      - php-log:/var/log/php-fpm
    networks:
      - php_network

  php-fpm:
    container_name: nav-php-fpm
    build:
      context: .
      dockerfile: Dockerfile.php
    command: ["php-fpm", "-F", "-y", "/usr/local/etc/php-fpm.d/www.conf"]
    ports:
      - "9888:9001"
    volumes:
      - ./nav/html:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - php-socket:/var/run/php
      - php-log:/var/log/php-fpm
    networks:
      - php_network

networks:
  php_network:
    driver: bridge

volumes:
  php-socket:
  php-log:


## 执行命令 
## docker-compose -f docker-compose-nav down
## docker-compose -f docker-compose-nav down