version: '3'
services:
  web:
    container_name: resume-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf

  nav:
    container_name: nav
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nav/certs:/etc/nginx/nav/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
