version: '3'
services:
  web:
    container_name: resume-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html # 主站点静态文件

  nav:
    container_name: nav
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80" # 只暴露给内部网络
    volumes:
      - ./nav/certs:/etc/nginx/nav/ssl
      - ./nav/nginx.conf:/etc/nginx/conf.d/nav.conf # 子站点专用配置
      - ./nav/html:/usr/share/nginx/html # 子站点静态文件

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./nav/html:/var/www/html # PHP文件目录
    restart: always
